# - Try to find the cppcms library
# Once done this will define
#
#  CPPCS_FOUND - System has cppcms
#  CPPCMS_INCLUDE_DIR - The cppcms include directory
#  CPPCMS_LIBRARIES - The libraries needed to use cppcms


FIND_PATH( CPPCMS_INCLUDE_DIR cppcms/application.h)
FIND_LIBRARY( CPPCMS_LIBRARIES NAMES cppcms)
FIND_LIBRARY( LIBBOOSTER_LIBRARY NAMES booster)

IF( CPPCMS_INCLUDE_DIR AND CPPCMS_LIBRARIES AND LIBBOOSTER_LIBRARY )
   SET( CPPCMS_FOUND TRUE )
   SET( CPPCMS_LIBRARIES ${CPPCMS_LIBRARIES} ${LIBBOOSTER_LIBRARY})
ENDIF( CPPCMS_INCLUDE_DIR AND CPPCMS_LIBRARIES AND LIBBOOSTER_LIBRARY )

IF( CPPCMS_FOUND )
   IF( NOT CPPCMS_FIND_QUIETLY )
       MESSAGE( STATUS "Found libcppcms: ${CPPCMS_LIBRARIES}" )
      MESSAGE( STATUS "Found libbooster: ${LIBBOOSTER_LIBRARY}" )
   ENDIF( NOT CPPCMS_FIND_QUIETLY )
ELSE( CPPCMS_FOUND )
   IF( CPPCMS_FIND_REQUIRED )
      MESSAGE( FATAL_ERROR "Could not find libcppcms" )
   ENDIF( CPPCMS_FIND_REQUIRED )
ENDIF( CPPCMS_FOUND )
